default_connection: &DEFAULT
  host: fastdb.c3.unam.mx
  user: monitor
  password: monitor123
  port: 5433

plataforma:
  name: Configuracion de default (INEGI)

fuente_de_datos_metadatos:
  epi_puma_censo_inegi_2020: 
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - name
      - interval
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state
      ageb: cells_ageb
    categorias: 
      archivo: epi_puma_censo_sql.py

  INEGI:  # Nombre a elegir al gusto
    conexion: endpoints
    variables: http://chilamdev.c3.unam.mx:2112/variables
    get_data: http://chilamdev.c3.unam.mx:2112/get-data