
# https://camel.readthedocs.io/en/latest/yamlref.html

# <<<Configuración de default>>>

# En plataforma se inidica un nombre para la misma.

# id_column es la columna donde está los id's de las variables.
# variable_columns es una lista de las columnas que definen a las variables.
# table es la tabla donde están almacenados los datos
# resolution indica la columna donde están las celdas para cada resolución del ensamble.
# categorias:
# -> Diccionario key='archivo', value: file.py con sql indicando cómo agrupar las variables.
# -> Diccionario key='columnas', value: lista indicando las columnas con las cuáles agrupar de forma ordenada.
# -> Null en caso de no tener las dos opciones anteriores.

default_connection: &DEFAULT
  host: fastdb.c3.unam.mx
  user: monitor
  password: monitor123
  port: 5433

plataforma:
  name: Configuracion de default (INEGI)

conexion: postgresql

fuente_de_datos_metadatos:
  epi_puma_censo_inegi_2020: 
    <<: *DEFAULT
    id_column: id
    variable_columns:
      - name
      - interval
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state
      ageb: cells_ageb
    categorias: 
      archivo: epi_puma_censo_sql.py
# Acomodo indicado en un archivo con sql