
# <<<Configuración con todas las fuentes de datos disponibles (postgresql & endpoints)>>>

default_connection: &DEFAULT
  host: fastdb.c3.unam.mx
  user: monitor
  password: monitor123
  port: 5433

plataforma:
  name: Miscelaneo

fuente_de_datos_metadatos:
  epi_puma_censo_inegi_2020_monitor: 
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - name
      - interval
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state
    categorias: 
      archivo: epi_puma_censo_sql.py
  
  INEGI (endpoints):
    conexion: endpoints
    variables: http://chilamdev.c3.unam.mx:2112/variables
    get_data: http://chilamdev.c3.unam.mx:2112/get-data

  epi_puma_worldclim:
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
        - label
        - interval
    table: covariable
    resolution:
      mun: cells_mun
    categorias: Null

  epi_puma_accidentes:
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - name
      - interval
    table: covariable
    resolution:
      mun: cells_mun
    categorias: Null

  newspecies:
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - especievalida
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state
    categorias: 
      columnas:
        - reinovalido
        - phylumdivisionvalido
        - clasevalida
        - ordenvalido
        - familiavalida
        - generovalido

  epi_puma_hospederos:
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - nombrecientifico
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state
    categorias: 
      columnas:
        - reino
        - phylum
        - clase
        - orden
        - familia
        - genero

  Personas:
    <<: *DEFAULT
    conexion: postgresql
    id_column: id
    variable_columns:
      - valor
    table: covariable
    resolution:
      UNAM_1075: presencias
    categorias:
      columnas:
        - nombre