
# https://camel.readthedocs.io/en/latest/yamlref.html

# <<<Configuraci칩n de default>>>

# En plataforma se inidica un nombre para la misma.

# variable_columns es una lista de las columnas que definen a las variables.
# table es la tabla donde est치n almacenados los datos
# resolution indica la columna donde est치n las celdas para cada resoluci칩n del ensamble.

default_connection: &DEFAULT
  host: fastdb.c3.unam.mx
  user: monitor
  password: monitor123
  port: 5433

plataforma:
  name: Configuracion de default (INEGI)

fuente_de_datos_metadatos:
  epi_puma_censo_inegi_2020: 
    <<: *DEFAULT
    variable_columns:
      - name
      - interval
    table: covariable
    resolution:
      ageb: cells_ageb
      mun: cells_mun
      state: cells_state
    # categorias:
    #   columnas:
    #     name:
    #       condicion 1: 
    #         - grado 1
    #         - grado 2
    #         - metadato:
    #           - estudios
    #           - escolaridad

  epi_puma_worldclim:
    <<: *DEFAULT
    variable_columns:
      - label
      - interval
    table: covariable
    resolution:
      mun: cells_mun
      state: cells_state